2D arrays

1. Create an array of size [10,50] and use the random function to fill it with integers between 1 and 500 (inclusive). Load it to a DataFrame.

2. Calculate the sum of each row; the sum of each column; and the sum of all entries.

3. Determine the minimum; maximum; average; and standard deviation of all entries.

4. Sort the DataFrame: by rows, by columns, on row 2, on column 2.

*Note â€“ you should first write your program with a smaller array (perhaps [3,2] to make sure you get it running correctly. Then modify your program to meet the size requirements [10,50].

In [77]:
# 1. Create an array of size [10,50] and 
# use the random function to fill it with integers between 1 and 500 (inclusive).
import numpy as np
import pandas as pd

rows = 10
cols = 50
minVal = 1
maxVal = 501 # excludes this

arr = np.random.randint(minVal,maxVal,rows*cols)

print(arr)

newarr = arr.reshape(rows, cols)

print(newarr)

# Load it to a DataFrame.

index = ['Row'+str(i) for i in range(1, rows+1)]
columns = ['Column'+str(i) for i in range(1, cols+1)]

#print(index)
#print(columns)

df = pd.DataFrame(data=newarr, index=index, columns=columns)
#df = pd.DataFrame.from_records(arr)

print(df)

[348  75 108 261   4 211 368 198 226 168 251 379  81 125  95  16  50  80
 201 230  90 402 137 161  69  51  30 464  24 164 224 457 161 297 323 319
 458 470 371  22 415 115  91 244 239 192 485 231 212 105 179  26 297 156
 295 117  81 267 171 277 387 375 148 445 113  51 359 278  39 371 331 100
 216  45 424 421 496 127 371 388  63 461 183  24 398   5 103 103  45 344
 163 254 434 390 396 415 268 189  53 348 183  94 127 371 458 110 195 315
 399 241  45  64 198  61 113 427  70 217 402 412 240 188  41 105 256 478
 341 231 232  18  33 127   4 352 218 455 383 257  23 320 368 488  94 296
 330 360  56   5  34  26  85 383 150 341 354 239 415  84 429 158 251 164
 143 426 226 132 251 215 151 344 233 418 184 453 357  15 311  11 320 131
 122 110 469 293 395 216 154 409 283 102  64 160 453 195 397 314 109 134
 312 146 369 233  77 298 388  12  63  33 402 265 197 398 488 486 349 427
 163 413 222 369 392 342 140 447 383 152 213 211 335 439 393 135 398  65
 295 367 470 300 140 245 293 312 400  38 454  24 292 413 346 314 161  78
 360 227 390  20 214 470 156 299 472 214 272 228 203 295 204 337 141 251
   2 412 463 140 338 319  66  25 103 444 217 245 493 276 139 498 362  17
 245 390 312  67 426   6 172 194 120  71 340 179  58 168 105  52 372 135
 280  70 357  69 341 246 423 387 331 433 339 328 119 244 259 247 397 387
  30 110  83 250 477 228 155  65 484 223 183 146 446 430  83 312 286  62
  80 404  82 456 250 386 299 139 256 495 446 336 301 155  75 286 324 307
   7 361 271 432  47 230 100 308  20 320 102 459 374 151 355 236 278  51
 488 360 498 192 170 325 201 424 201 404 476 466  86 499  97  34 400  14
 141 337 232 164 274 376 134 328 259 464 359 139 376 467 408 474 199 318
  69 125 430 288 367 270 260 463 481 213 455 114 453 298 442 257 217 322
 279 189 149 495 195 188 321  81  83 129 498 198 365 306 462 228 424 392
 396 153 469 487 328 455 416 226 244 269 268 465 269 313 185 244 324 155
  95 275  71 392 238  55 305 232 280 342 228 418 110  18 442  55  56 182
 179 143 207 197 310 499 157 258 456 494 284 406 342 284]
[[348  75 108 261   4 211 368 198 226 168 251 379  81 125  95  16  50  80
  201 230  90 402 137 161  69  51  30 464  24 164 224 457 161 297 323 319
  458 470 371  22 415 115  91 244 239 192 485 231 212 105]
 [179  26 297 156 295 117  81 267 171 277 387 375 148 445 113  51 359 278
   39 371 331 100 216  45 424 421 496 127 371 388  63 461 183  24 398   5
  103 103  45 344 163 254 434 390 396 415 268 189  53 348]
 [183  94 127 371 458 110 195 315 399 241  45  64 198  61 113 427  70 217
  402 412 240 188  41 105 256 478 341 231 232  18  33 127   4 352 218 455
  383 257  23 320 368 488  94 296 330 360  56   5  34  26]
 [ 85 383 150 341 354 239 415  84 429 158 251 164 143 426 226 132 251 215
  151 344 233 418 184 453 357  15 311  11 320 131 122 110 469 293 395 216
  154 409 283 102  64 160 453 195 397 314 109 134 312 146]
 [369 233  77 298 388  12  63  33 402 265 197 398 488 486 349 427 163 413
  222 369 392 342 140 447 383 152 213 211 335 439 393 135 398  65 295 367
  470 300 140 245 293 312 400  38 454  24 292 413 346 314]
 [161  78 360 227 390  20 214 470 156 299 472 214 272 228 203 295 204 337
  141 251   2 412 463 140 338 319  66  25 103 444 217 245 493 276 139 498
  362  17 245 390 312  67 426   6 172 194 120  71 340 179]
 [ 58 168 105  52 372 135 280  70 357  69 341 246 423 387 331 433 339 328
  119 244 259 247 397 387  30 110  83 250 477 228 155  65 484 223 183 146
  446 430  83 312 286  62  80 404  82 456 250 386 299 139]
 [256 495 446 336 301 155  75 286 324 307   7 361 271 432  47 230 100 308
   20 320 102 459 374 151 355 236 278  51 488 360 498 192 170 325 201 424
  201 404 476 466  86 499  97  34 400  14 141 337 232 164]
 [274 376 134 328 259 464 359 139 376 467 408 474 199 318  69 125 430 288
  367 270 260 463 481 213 455 114 453 298 442 257 217 322 279 189 149 495
  195 188 321  81  83 129 498 198 365 306 462 228 424 392]
 [396 153 469 487 328 455 416 226 244 269 268 465 269 313 185 244 324 155
   95 275  71 392 238  55 305 232 280 342 228 418 110  18 442  55  56 182
  179 143 207 197 310 499 157 258 456 494 284 406 342 284]]
       Column1  Column2  Column3  Column4  Column5  Column6  Column7  Column8  \
Row1       348       75      108      261        4      211      368      198
Row2       179       26      297      156      295      117       81      267
Row3       183       94      127      371      458      110      195      315
Row4        85      383      150      341      354      239      415       84
Row5       369      233       77      298      388       12       63       33
Row6       161       78      360      227      390       20      214      470
Row7        58      168      105       52      372      135      280       70
Row8       256      495      446      336      301      155       75      286
Row9       274      376      134      328      259      464      359      139
Row10      396      153      469      487      328      455      416      226

       Column9  Column10  ...  Column41  Column42  Column43  Column44  \
Row1       226       168  ...       415       115        91       244
Row2       171       277  ...       163       254       434       390
Row3       399       241  ...       368       488        94       296
Row4       429       158  ...        64       160       453       195
Row5       402       265  ...       293       312       400        38
Row6       156       299  ...       312        67       426         6
Row7       357        69  ...       286        62        80       404
Row8       324       307  ...        86       499        97        34
Row9       376       467  ...        83       129       498       198
Row10      244       269  ...       310       499       157       258

       Column45  Column46  Column47  Column48  Column49  Column50
Row1        239       192       485       231       212       105
Row2        396       415       268       189        53       348
Row3        330       360        56         5        34        26
Row4        397       314       109       134       312       146
Row5        454        24       292       413       346       314
Row6        172       194       120        71       340       179
Row7         82       456       250       386       299       139
Row8        400        14       141       337       232       164
Row9        365       306       462       228       424       392
Row10       456       494       284       406       342       284

[10 rows x 50 columns]

In [78]:
# 2. Calculate the sum of each row; the sum of each column; and the sum of all entries.
print("Sum")
print(df.sum(axis=1))
print(df.sum(axis=0))
print("Sum of all entries:",df.sum().sum())

Sum
Row1     10498
Row2     11990
Row3     10861
Row4     12211
Row5     14400
Row6     12073
Row7     12296
Row8     13292
Row9     15081
Row10    13676
dtype: int64
Column1     2309
Column2     2081
Column3     2273
Column4     2857
Column5     3149
Column6     1918
Column7     2466
Column8     2088
Column9     3084
Column10    2520
Column11    2627
Column12    3140
Column13    2492
Column14    3221
Column15    1731
Column16    2380
Column17    2290
Column18    2619
Column19    1757
Column20    3086
Column21    1980
Column22    3423
Column23    2671
Column24    2157
Column25    2972
Column26    2128
Column27    2551
Column28    2010
Column29    3020
Column30    2847
Column31    2032
Column32    2132
Column33    3083
Column34    2099
Column35    2357
Column36    3107
Column37    2951
Column38    2721
Column39    2194
Column40    2479
Column41    2380
Column42    2585
Column43    2730
Column44    2063
Column45    3291
Column46    2769
Column47    2467
Column48    2400
Column49    2594
Column50    2097
dtype: int64
Sum of all entries: 126378

In [79]:
# 3. Determine the minimum; maximum; average; and standard deviation of all entries.
print("Minimum of all entries:", df.min().min())
print("Maximum of all entries:", df.max().max())
# df.mean().mean() also works
print("Average of all entries:", df.stack().mean())
print("Standard Deviation of all entries:", df.stack().std())

Minimum of all entries: 2
Maximum of all entries: 499
Average of all entries: 252.756
Standard Deviation of all entries: 140.1710108709256

In [80]:
# 4. Sort the DataFrame: by rows, by columns, on row 2, on column 2.
print("Actual DF")
print(df)

print("Sort by Row2")
print(df.sort_values(by = 'Row2', axis = 1))

print("Sort by Column2")
print(df.sort_values('Column2'))

Actual DF
       Column1  Column2  Column3  Column4  Column5  Column6  Column7  Column8  \
Row1       348       75      108      261        4      211      368      198
Row2       179       26      297      156      295      117       81      267
Row3       183       94      127      371      458      110      195      315
Row4        85      383      150      341      354      239      415       84
Row5       369      233       77      298      388       12       63       33
Row6       161       78      360      227      390       20      214      470
Row7        58      168      105       52      372      135      280       70
Row8       256      495      446      336      301      155       75      286
Row9       274      376      134      328      259      464      359      139
Row10      396      153      469      487      328      455      416      226

       Column9  Column10  ...  Column41  Column42  Column43  Column44  \
Row1       226       168  ...       415       115        91       244
Row2       171       277  ...       163       254       434       390
Row3       399       241  ...       368       488        94       296
Row4       429       158  ...        64       160       453       195
Row5       402       265  ...       293       312       400        38
Row6       156       299  ...       312        67       426         6
Row7       357        69  ...       286        62        80       404
Row8       324       307  ...        86       499        97        34
Row9       376       467  ...        83       129       498       198
Row10      244       269  ...       310       499       157       258

       Column45  Column46  Column47  Column48  Column49  Column50
Row1        239       192       485       231       212       105
Row2        396       415       268       189        53       348
Row3        330       360        56         5        34        26
Row4        397       314       109       134       312       146
Row5        454        24       292       413       346       314
Row6        172       194       120        71       340       179
Row7         82       456       250       386       299       139
Row8        400        14       141       337       232       164
Row9        365       306       462       228       424       392
Row10       456       494       284       406       342       284

[10 rows x 50 columns]
Sort by Row2
       Column36  Column34  Column2  Column19  Column24  Column39  Column16  \
Row1        319       297       75       201       161       371        16
Row2          5        24       26        39        45        45        51
Row3        455       352       94       402       105        23       427
Row4        216       293      383       151       453       283       132
Row5        367        65      233       222       447       140       427
Row6        498       276       78       141       140       245       295
Row7        146       223      168       119       387        83       433
Row8        424       325      495        20       151       476       230
Row9        495       189      376       367       213       321       125
Row10       182        55      153        95        55       207       244

       Column49  Column31  Column7  ...  Column44  Column45  Column35  \
Row1        212       224      368  ...       244       239       323
Row2         53        63       81  ...       390       396       398
Row3         34        33      195  ...       296       330       218
Row4        312       122      415  ...       195       397       395
Row5        346       393       63  ...        38       454       295
Row6        340       217      214  ...         6       172       139
Row7        299       155      280  ...       404        82       183
Row8        232       498       75  ...        34       400       201
Row9        424       217      359  ...       198       365       149
Row10       342       110      416  ...       258       456        56

       Column46  Column26  Column25  Column43  Column14  Column32  Column27
Row1        192        51        69        91       125       457        30
Row2        415       421       424       434       445       461       496
Row3        360       478       256        94        61       127       341
Row4        314        15       357       453       426       110       311
Row5         24       152       383       400       486       135       213
Row6        194       319       338       426       228       245        66
Row7        456       110        30        80       387        65        83
Row8         14       236       355        97       432       192       278
Row9        306       114       455       498       318       322       453
Row10       494       232       305       157       313        18       280

[10 rows x 50 columns]
Sort by Column2
       Column1  Column2  Column3  Column4  Column5  Column6  Column7  Column8  \
Row2       179       26      297      156      295      117       81      267
Row1       348       75      108      261        4      211      368      198
Row6       161       78      360      227      390       20      214      470
Row3       183       94      127      371      458      110      195      315
Row10      396      153      469      487      328      455      416      226
Row7        58      168      105       52      372      135      280       70
Row5       369      233       77      298      388       12       63       33
Row9       274      376      134      328      259      464      359      139
Row4        85      383      150      341      354      239      415       84
Row8       256      495      446      336      301      155       75      286

       Column9  Column10  ...  Column41  Column42  Column43  Column44  \
Row2       171       277  ...       163       254       434       390
Row1       226       168  ...       415       115        91       244
Row6       156       299  ...       312        67       426         6
Row3       399       241  ...       368       488        94       296
Row10      244       269  ...       310       499       157       258
Row7       357        69  ...       286        62        80       404
Row5       402       265  ...       293       312       400        38
Row9       376       467  ...        83       129       498       198
Row4       429       158  ...        64       160       453       195
Row8       324       307  ...        86       499        97        34

       Column45  Column46  Column47  Column48  Column49  Column50
Row2        396       415       268       189        53       348
Row1        239       192       485       231       212       105
Row6        172       194       120        71       340       179
Row3        330       360        56         5        34        26
Row10       456       494       284       406       342       284
Row7         82       456       250       386       299       139
Row5        454        24       292       413       346       314
Row9        365       306       462       228       424       392
Row4        397       314       109       134       312       146
Row8        400        14       141       337       232       164

[10 rows x 50 columns]